services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
      - 9000:9000
     labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helpdesk.rule=Host(`helpdesk.orthanc.fun`)"
      - "traefik.http.routers.helpdesk.service=whatsapp"
      - "traefik.http.services.helpdesk.loadbalancer.server.port=4400"

      - "traefik.http.routers.helpdesk-web.rule=Host(`helpdesk.orthanc.fun`)"
      - "traefik.http.routers.helpdesk-web.entrypoints=web"
      - "traefik.http.routers.helpdesk-web.middlewares=helpdesk-redirect"
      - "traefik.http.middlewares.helpdesk-redirect.redirectscheme.scheme=https"

      - "traefik.http.routers.helpdesk.rule=Host(`helpdesk.orthanc.fun`)"
      - "traefik.http.routers.helpdesk.entrypoints=websecure"
      - "traefik.http.routers.helpdesk.tls=true"
      - "traefik.http.routers.helpdesk.tls.certresolver=letsencrypt" 


volumes:
  mariadb-data:

networks:
  dokploy-network:
    external: true
    
