services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - dokploy-network

  redis:
    image: redis:alpine
    networks:
      - dokploy-network

  frappe:
    image: frappe/bench:latest
    command:
      - bash
      - -c
      - >
        if [ ! -f /workspace/init.sh ]; then
          echo 'Downloading init.sh...';
          if command -v wget >/dev/null 2>&1; then
            wget -q -O /workspace/init.sh https://raw.githubusercontent.com/frappe/helpdesk/develop/docker/init.sh;
          else
            curl -fsSL -o /workspace/init.sh https://raw.githubusercontent.com/frappe/helpdesk/develop/docker/init.sh;
          fi;
          chmod +x /workspace/init.sh;
        fi;
        /workspace/init.sh
    
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - .:/workspace
    labels:
      - "traefik.enable=true"

      # Redirect HTTP -> HTTPS
      - "traefik.http.routers.helpdesk-web.rule=Host(`helpdesk.orthanc.fun`)"
      - "traefik.http.routers.helpdesk-web.entrypoints=web"
      - "traefik.http.routers.helpdesk-web.middlewares=helpdesk-redirect"
      - "traefik.http.middlewares.helpdesk-redirect.redirectscheme.scheme=https"

      # HTTPS router
      - "traefik.http.routers.helpdesk.rule=Host(`helpdesk.orthanc.fun`)"
      - "traefik.http.routers.helpdesk.entrypoints=websecure"
      - "traefik.http.routers.helpdesk.tls=true"
      - "traefik.http.routers.helpdesk.tls.certresolver=letsencrypt"
      - "traefik.http.routers.helpdesk.service=helpdesk"

      # Service configuration (adjust port if your app listens on a different internal port)
      - "traefik.http.services.helpdesk.loadbalancer.server.port=8000"
    networks:
      - dokploy-network

volumes:
  mariadb-data:

networks:
  dokploy-network:
    external: true
